import type { Order } from "@/lib/orders/config"

export const MOCK_ORDERS = [
  {
    id: "INV/20260826/HG/0184",
    status: "unpaid",
    paymentStatus: "pending",
    sourceKind: "cart",
    fulfillmentStatus: "awaiting_payment",
    placedAt: "2026-08-26T09:14:00+07:00",
    courier: "JNE Reguler",
    shippingCourier: "jne",
    shipping: 24000,
    paymentToken: null,
    tracking: null,
    items: [
      {
        productSlug: "jaket-kamuflase-bottomland",
        name: "Jaket Kamuflase Bottomland",
        variant: "Ukuran L",
        quantity: 1,
        price: 685000,
      },
      {
        productSlug: "sarung-tangan-taktis",
        name: "Sarung Tangan Taktis",
        variant: "Hitam / M",
        quantity: 2,
        price: 145000,
      },
    ],
  },
  {
    id: "INV/20260821/HG/0177",
    status: "processing",
    paymentStatus: "paid",
    sourceKind: "cart",
    fulfillmentStatus: "processing",
    placedAt: "2026-08-21T16:02:00+07:00",
    courier: "SiCepat BEST",
    shippingCourier: "sicepat",
    shipping: 32000,
    paymentToken: null,
    tracking: null,
    items: [
      {
        productSlug: "reel-spinning-4000-series",
        name: "Reel Spinning 4000 Series",
        variant: "Gear ratio 5.2:1",
        quantity: 1,
        price: 1250000,
      },
    ],
  },
  {
    id: "INV/20260814/HG/0162",
    status: "shipped",
    paymentStatus: "paid",
    sourceKind: "cart",
    fulfillmentStatus: "shipped",
    placedAt: "2026-08-14T11:38:00+07:00",
    courier: "J&T Express",
    shippingCourier: "jnt",
    shipping: 28000,
    paymentToken: null,
    tracking: "JT4820193857",
    items: [
      {
        productSlug: "joran-carbon-fiber-210-cm",
        name: "Joran Carbon Fiber 210 cm",
        variant: "Medium action",
        quantity: 1,
        price: 780000,
      },
      {
        productSlug: "kotak-umpan-6-sekat",
        name: "Kotak Umpan 6 Sekat",
        variant: "Bening",
        quantity: 1,
        price: 95000,
      },
    ],
  },
  {
    id: "INV/20260802/HG/0139",
    status: "completed",
    paymentStatus: "paid",
    sourceKind: "cart",
    fulfillmentStatus: "completed",
    placedAt: "2026-08-02T08:20:00+07:00",
    courier: "JNE YES",
    shippingCourier: "jne",
    shipping: 41000,
    paymentToken: null,
    tracking: "JNE0099213847",
    items: [
      {
        productSlug: "tenda-dome-2-orang",
        name: "Tenda Dome 2 Orang",
        variant: "Olive",
        quantity: 1,
        price: 1180000,
      },
    ],
  },
  {
    id: "INV/20260729/HG/0128",
    status: "cancelled",
    paymentStatus: "cancelled",
    sourceKind: "cart",
    fulfillmentStatus: "cancelled",
    placedAt: "2026-07-29T19:45:00+07:00",
    courier: "AnterAja Reguler",
    shippingCourier: "manual",
    shipping: 22000,
    paymentToken: null,
    tracking: null,
    items: [
      {
        productSlug: "sparepart-piston-set",
        name: "Sparepart Piston Set",
        variant: "Kaliber 5.5 mm",
        quantity: 1,
        price: 320000,
      },
    ],
  },
] as const satisfies readonly Order[]
