import type { Product } from "@/lib/products/config"

export const MOCK_PRODUCTS = [
  {
    slug: "jaket-kamuflase-bottomland",
    name: "Jaket Kamuflase Bottomland Tahan Angin",
    category: "hunting",
    price: 685000,
    compareAtPrice: 850000,
    stock: 18,
    sold: 1240,
    description: [
      "Jaket kamuflase dengan motif Bottomland yang menyatu dengan ranting dan kulit kayu, cocok untuk berburu di hutan dataran rendah.",
      "Lapisan luar tahan angin dan gerimis, sementara bagian dalam dilapisi fleece tipis agar tetap hangat tanpa membatasi gerakan saat menarik busur.",
      "Empat kantong depan berpenutup velcro senyap, ditambah satu kantong dada untuk kompas atau radio.",
    ],
    images: [
      { id: "depan", alt: "Jaket kamuflase Bottomland dilihat dari depan." },
      { id: "belakang", alt: "Bagian belakang jaket dengan tudung terlipat." },
      { id: "detail-kantong", alt: "Detail kantong dada berpenutup velcro." },
      { id: "dipakai", alt: "Jaket dipakai model di area berhutan." },
    ],
    variants: [
      { label: "Ukuran", options: ["M", "L", "XL", "XXL"] },
      { label: "Motif", options: ["Bottomland", "Edge", "Timber"] },
    ],
    ratings: { 5: 96, 4: 24, 3: 6, 2: 1, 1: 1 },
    reviews: [
      {
        id: "ulasan-jaket-1",
        author: "Bagas P.",
        rating: 5,
        createdAt: "2026-08-12T10:20:00+07:00",
        variant: "Ukuran L / Bottomland",
        body: "Motifnya benar-benar menyatu dengan semak. Dipakai subuh di kebun karet, angin tidak masuk sama sekali. Ukuran L pas untuk badan 175 cm.",
      },
      {
        id: "ulasan-jaket-2",
        author: "Rian S.",
        rating: 4,
        createdAt: "2026-07-29T19:05:00+07:00",
        variant: "Ukuran XL / Bottomland",
        body: "Bahan tebal dan kantongnya senyap, cuma jahitan tudung agak kaku di awal. Setelah dua kali dipakai sudah nyaman.",
      },
      {
        id: "ulasan-jaket-3",
        author: "Dwi H.",
        rating: 5,
        createdAt: "2026-07-04T08:40:00+07:00",
        variant: "Ukuran M / Timber",
        body: "Pengiriman cepat, jaket dibungkus rapi. Sudah dipakai dua kali hujan ringan dan air masih mengalir di permukaan.",
      },
    ],
  },
  {
    slug: "sarung-tangan-taktis-anti-slip",
    name: "Sarung Tangan Taktis Anti Slip",
    category: "hunting",
    price: 145000,
    compareAtPrice: null,
    stock: 64,
    sold: 890,
    description: [
      "Telapak berbahan karet bertekstur untuk cengkeraman kuat pada gagang basah, dengan bantalan tipis di pangkal telapak.",
      "Ujung jari telunjuk dan jempol dilapisi bahan konduktif sehingga ponsel tetap bisa dioperasikan tanpa melepas sarung tangan.",
    ],
    images: [
      { id: "pasang", alt: "Sepasang sarung tangan taktis warna hitam." },
      { id: "telapak", alt: "Detail telapak karet bertekstur." },
      { id: "pergelangan", alt: "Penutup pergelangan dengan velcro." },
    ],
    variants: [
      { label: "Ukuran", options: ["M", "L", "XL"] },
      { label: "Warna", options: ["Hitam", "Olive", "Coyote"] },
    ],
    ratings: { 5: 52, 4: 18, 3: 4, 2: 2, 1: 0 },
    reviews: [
      {
        id: "ulasan-sarung-1",
        author: "Yoga A.",
        rating: 5,
        createdAt: "2026-08-02T13:15:00+07:00",
        variant: "Hitam / L",
        body: "Grip mantap walau tangan berkeringat. Fitur layar sentuhnya benar-benar berfungsi, tidak perlu buka tutup sarung tangan lagi.",
      },
      {
        id: "ulasan-sarung-2",
        author: "Fajar N.",
        rating: 4,
        createdAt: "2026-06-21T09:00:00+07:00",
        variant: "Olive / M",
        body: "Nyaman dan tidak panas. Ukuran M sedikit sempit di pangkal jempol, mungkin lebih baik ambil satu nomor di atas.",
      },
    ],
  },
  {
    slug: "tas-punggung-hunting-45l",
    name: "Tas Punggung Hunting 45L Rangka Internal",
    category: "hunting",
    price: 520000,
    compareAtPrice: 640000,
    stock: 12,
    sold: 315,
    description: [
      "Kapasitas 45 liter dengan rangka internal alumunium yang memindahkan beban ke pinggul, nyaman untuk perjalanan dua hari.",
      "Dilengkapi dudukan busur atau senapan di bagian depan, kantong hidrasi 2 liter, dan sarung hujan yang tersimpan di dasar tas.",
    ],
    images: [
      { id: "depan", alt: "Tas punggung hunting 45 liter warna olive." },
      { id: "punggung", alt: "Sistem punggung dengan rangka internal." },
      { id: "terbuka", alt: "Kompartemen utama tas dalam keadaan terbuka." },
      { id: "sarung-hujan", alt: "Sarung hujan terpasang menutupi tas." },
    ],
    variants: [{ label: "Warna", options: ["Olive", "Coyote", "Kamuflase"] }],
    ratings: { 5: 31, 4: 9, 3: 2, 2: 0, 1: 0 },
    reviews: [
      {
        id: "ulasan-tas-1",
        author: "Hendra W.",
        rating: 5,
        createdAt: "2026-08-18T16:30:00+07:00",
        variant: "Olive",
        body: "Beban 15 kg terasa ringan karena tumpuannya di pinggul. Dudukan busur kokoh, tidak goyang saat menembus semak.",
      },
    ],
  },
  {
    slug: "teropong-monokuler-10x42",
    name: "Teropong Monokuler 10x42 Lensa Multi-Coated",
    category: "hunting",
    price: 1350000,
    compareAtPrice: null,
    stock: 7,
    sold: 96,
    description: [
      "Perbesaran 10x dengan lensa objektif 42 mm memberi gambar terang bahkan saat cahaya mulai turun di jam-jam terbaik berburu.",
      "Bodi berlapis karet kedap embun dengan pengisian nitrogen, aman dipakai di kabut dan gerimis. Ringan dan cukup untuk satu tangan.",
    ],
    images: [
      { id: "bodi", alt: "Teropong monokuler 10x42 berlapis karet hitam." },
      {
        id: "lensa",
        alt: "Lensa objektif dengan pantulan hijau multi-coated.",
      },
      { id: "genggam", alt: "Monokuler digenggam satu tangan." },
    ],
    variants: [{ label: "Paket", options: ["Standar", "Plus tripod mini"] }],
    ratings: { 5: 14, 4: 5, 3: 1, 2: 0, 1: 0 },
    reviews: [
      {
        id: "ulasan-teropong-1",
        author: "Sigit R.",
        rating: 5,
        createdAt: "2026-08-20T07:10:00+07:00",
        variant: "Plus tripod mini",
        body: "Terang sekali untuk kelas harganya. Dipakai memantau punggungan bukit jam lima pagi, detail masih terbaca jelas.",
      },
    ],
  },
  {
    slug: "joran-carbon-fiber-210",
    name: "Joran Carbon Fiber 210 cm Medium Action",
    category: "fishing",
    price: 780000,
    compareAtPrice: 950000,
    stock: 23,
    sold: 1580,
    description: [
      "Blank carbon 24T yang ringan namun responsif, mengangkat ikan sedang tanpa membebani pergelangan sepanjang hari.",
      "Ring keramik mengurangi gesekan senar dan tahan terhadap braid. Gagang EVA padat tetap nyaman digenggam saat basah.",
      "Terbagi dua sambungan sehingga mudah masuk ke tas motor maupun bagasi.",
    ],
    images: [
      {
        id: "utuh",
        alt: "Joran carbon fiber 210 cm dalam keadaan tersambung.",
      },
      { id: "gagang", alt: "Gagang EVA dengan dudukan reel." },
      { id: "ring", alt: "Detail ring keramik pada batang joran." },
      { id: "aksi", alt: "Joran melengkung saat menarik ikan." },
    ],
    variants: [
      { label: "Panjang", options: ["180 cm", "210 cm", "240 cm"] },
      { label: "Action", options: ["Light", "Medium", "Medium Heavy"] },
    ],
    ratings: { 5: 128, 4: 41, 3: 9, 2: 3, 1: 2 },
    reviews: [
      {
        id: "ulasan-joran-1",
        author: "Arif M.",
        rating: 5,
        createdAt: "2026-08-24T17:45:00+07:00",
        variant: "210 cm / Medium",
        body: "Ringan tapi tidak murahan. Dipakai casting dari perahu setengah hari, pergelangan tidak pegal. Ring rapi tanpa lem berlebih.",
      },
      {
        id: "ulasan-joran-2",
        author: "Wisnu T.",
        rating: 4,
        createdAt: "2026-08-09T06:25:00+07:00",
        variant: "240 cm / Medium Heavy",
        body: "Lentingannya bagus untuk umpan 20 gram. Sambungannya perlu dipastikan rapat sebelum dipakai, kalau tidak ada suara klik kecil.",
      },
      {
        id: "ulasan-joran-3",
        author: "Nanda K.",
        rating: 5,
        createdAt: "2026-07-15T14:00:00+07:00",
        variant: "210 cm / Light",
        body: "Sudah joran kedua yang saya beli di sini. Packing pakai pipa jadi aman sampai tujuan.",
      },
      {
        id: "ulasan-joran-4",
        author: "Bayu L.",
        rating: 3,
        createdAt: "2026-06-30T11:20:00+07:00",
        variant: "180 cm / Medium",
        body: "Kualitas sesuai harga, hanya saja gagang EVA sedikit licin saat berminyak. Sisanya tidak ada keluhan.",
      },
    ],
  },
  {
    slug: "reel-spinning-4000-series",
    name: "Reel Spinning 4000 Series 10 Ball Bearing",
    category: "fishing",
    price: 1250000,
    compareAtPrice: null,
    stock: 15,
    sold: 640,
    description: [
      "Bodi grafit dengan rotor seimbang, putarannya halus dari lemparan pertama sampai jam terakhir.",
      "Drag depan berbahan karbon dengan daya tahan 8 kg, cukup untuk ikan besar di muara maupun tepi laut.",
      "Spool alumunium dengan bibir teflon membantu lemparan lebih jauh dan mengurangi senar kusut.",
    ],
    images: [
      { id: "samping", alt: "Reel spinning 4000 series dilihat dari samping." },
      { id: "spool", alt: "Spool alumunium dengan bibir teflon." },
      { id: "handle", alt: "Handle reel dengan knob EVA." },
    ],
    variants: [{ label: "Seri", options: ["2000", "3000", "4000", "5000"] }],
    ratings: { 5: 47, 4: 12, 3: 3, 2: 1, 1: 0 },
    reviews: [
      {
        id: "ulasan-reel-1",
        author: "Galih S.",
        rating: 5,
        createdAt: "2026-08-15T18:50:00+07:00",
        variant: "4000",
        body: "Halus dan senyap. Drag-nya bisa diatur pelan-pelan, tidak langsung mengunci seperti reel sekelasnya.",
      },
      {
        id: "ulasan-reel-2",
        author: "Toni P.",
        rating: 4,
        createdAt: "2026-07-27T08:05:00+07:00",
        variant: "3000",
        body: "Berat pas untuk joran medium. Setelah dipakai di air laut wajib dibilas, kalau tidak knob mulai berdecit.",
      },
    ],
  },
  {
    slug: "kotak-umpan-6-sekat",
    name: "Kotak Umpan 6 Sekat Tahan Bocor",
    category: "fishing",
    price: 95000,
    compareAtPrice: 120000,
    stock: 80,
    sold: 2100,
    description: [
      "Enam sekat berukuran sama untuk memisahkan minnow, jig, dan kail tanpa saling mengait.",
      "Bodi polipropilena bening sehingga isi terlihat tanpa perlu dibuka, dengan pengunci karet yang menahan air masuk saat kotak terkena cipratan.",
    ],
    images: [
      { id: "tertutup", alt: "Kotak umpan bening dalam keadaan tertutup." },
      { id: "terbuka", alt: "Enam sekat kotak umpan dalam keadaan terbuka." },
    ],
    variants: [{ label: "Jumlah sekat", options: ["6 sekat", "12 sekat"] }],
    ratings: { 5: 88, 4: 30, 3: 11, 2: 2, 1: 1 },
    reviews: [
      {
        id: "ulasan-kotak-1",
        author: "Ilham D.",
        rating: 5,
        createdAt: "2026-08-06T12:30:00+07:00",
        variant: "6 sekat",
        body: "Murah, kuat, dan rapat. Sudah dua bulan dibawa naik perahu, belum ada air yang masuk ke dalam sekat.",
      },
      {
        id: "ulasan-kotak-2",
        author: "Prasetyo B.",
        rating: 4,
        createdAt: "2026-05-19T15:10:00+07:00",
        variant: "12 sekat",
        body: "Sekatnya rapi, tapi versi 12 agak sempit untuk minnow besar. Untuk jig kecil sangat pas.",
      },
    ],
  },
  {
    slug: "piston-set-kaliber-55",
    name: "Piston Set Kaliber 5.5 mm Bahan Kuningan",
    category: "spareparts",
    price: 320000,
    compareAtPrice: null,
    stock: 26,
    sold: 410,
    description: [
      "Piston kuningan yang dibubut presisi agar rapat di dalam silinder, mengurangi kebocoran udara pada tembakan pertama.",
      "Satu set berisi piston, dua seal cadangan, dan per pengganti. Pemasangan tidak memerlukan pembubutan ulang pada silinder standar.",
    ],
    images: [
      { id: "set", alt: "Satu set piston kuningan beserta seal dan per." },
      { id: "piston", alt: "Detail permukaan piston kuningan yang dibubut." },
    ],
    variants: [{ label: "Kaliber", options: ["4.5 mm", "5.5 mm", "6.35 mm"] }],
    ratings: { 5: 22, 4: 6, 3: 2, 2: 1, 1: 0 },
    reviews: [
      {
        id: "ulasan-piston-1",
        author: "Eko J.",
        rating: 5,
        createdAt: "2026-08-11T20:15:00+07:00",
        variant: "5.5 mm",
        body: "Presisi, langsung masuk tanpa diamplas. Tenaga naik lumayan dibanding piston lama yang sudah aus.",
      },
    ],
  },
  {
    slug: "per-gas-tuning-stainless",
    name: "Per Gas Tuning Stainless Steel",
    category: "spareparts",
    price: 185000,
    compareAtPrice: null,
    stock: 34,
    sold: 58,
    description: [
      "Per stainless steel yang digulung rapat dengan ujung digerinda datar, sehingga tekanan tetap merata pada setiap langkah.",
      "Tersedia tiga tingkat kekerasan agar tekanan bisa disesuaikan dengan panjang laras dan kaliber yang dipakai.",
    ],
    images: [
      { id: "per", alt: "Per gas tuning berbahan stainless steel." },
      { id: "ujung", alt: "Detail ujung per yang digerinda datar." },
    ],
    variants: [{ label: "Kekerasan", options: ["Soft", "Medium", "Hard"] }],
    ratings: { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 },
    reviews: [],
  },
  {
    slug: "tenda-dome-2-orang",
    name: "Tenda Dome 2 Orang Double Layer",
    category: "hobbies",
    price: 1180000,
    compareAtPrice: 1450000,
    stock: 9,
    sold: 275,
    description: [
      "Konstruksi double layer memisahkan flysheet dari inner tent sehingga uap embun tidak menetes ke dalam saat pagi.",
      "Flysheet berlapis PU 3000 mm sanggup menahan hujan deras, sementara inner mesh menjaga sirkulasi udara tetap jalan.",
      "Frame alumunium ringan dan berdiri sendiri, bisa dipindahkan setelah terpasang tanpa harus dibongkar.",
    ],
    images: [
      {
        id: "terpasang",
        alt: "Tenda dome dua orang terpasang di area terbuka.",
      },
      { id: "dalam", alt: "Bagian dalam tenda dengan inner mesh." },
      { id: "flysheet", alt: "Flysheet tenda saat terkena hujan." },
      { id: "kemasan", alt: "Tenda terlipat di dalam tas jinjingnya." },
    ],
    variants: [
      { label: "Kapasitas", options: ["2 orang", "4 orang"] },
      { label: "Warna", options: ["Olive", "Abu", "Oranye"] },
    ],
    ratings: { 5: 36, 4: 11, 3: 3, 2: 1, 1: 1 },
    reviews: [
      {
        id: "ulasan-tenda-1",
        author: "Rizal F.",
        rating: 5,
        createdAt: "2026-08-22T09:35:00+07:00",
        variant: "2 orang / Olive",
        body: "Kena hujan empat jam di Merbabu, bagian dalam tetap kering. Pasang sendiri butuh sepuluh menit saja.",
      },
      {
        id: "ulasan-tenda-2",
        author: "Ayu W.",
        rating: 4,
        createdAt: "2026-07-08T13:55:00+07:00",
        variant: "2 orang / Abu",
        body: "Luas untuk dua orang plus tas. Pasak bawaan agak lunak untuk tanah keras, sebaiknya bawa pasak tambahan.",
      },
    ],
  },
  {
    slug: "lampu-kepala-led-1200-lumen",
    name: "Lampu Kepala LED 1200 Lumen Isi Ulang",
    category: "hobbies",
    price: 165000,
    compareAtPrice: 210000,
    stock: 52,
    sold: 1830,
    description: [
      "Tiga mode putih dan satu mode merah, yang membuat mata tetap beradaptasi dengan gelap saat memeriksa peta atau ikan hasil tangkapan.",
      "Baterai 1200 mAh diisi lewat USB-C, penuh dalam dua jam dan tahan sembilan jam pada mode sedang.",
      "Bodi tahan cipratan dengan headband elastis yang bisa dilepas untuk dicuci.",
    ],
    images: [
      { id: "depan", alt: "Lampu kepala LED dengan headband elastis." },
      { id: "mode-merah", alt: "Lampu kepala menyala pada mode merah." },
      { id: "port", alt: "Port pengisian USB-C pada bodi lampu." },
    ],
    variants: [{ label: "Warna", options: ["Hitam", "Olive"] }],
    ratings: { 5: 141, 4: 38, 3: 8, 2: 4, 1: 2 },
    reviews: [
      {
        id: "ulasan-lampu-1",
        author: "Doni A.",
        rating: 5,
        createdAt: "2026-08-25T21:05:00+07:00",
        variant: "Hitam",
        body: "Terangnya jauh melebihi harga. Mode merah sangat membantu saat mengikat senar tanpa merusak penglihatan malam.",
      },
      {
        id: "ulasan-lampu-2",
        author: "Sari K.",
        rating: 4,
        createdAt: "2026-06-14T19:40:00+07:00",
        variant: "Olive",
        body: "Ringan dan tidak menekan dahi. Mode paling terang cepat menghabiskan baterai, jadi lebih sering pakai mode sedang.",
      },
    ],
  },
  {
    slug: "matras-lipat-alumunium-foil",
    name: "Matras Lipat Alumunium Foil Anti Lembap",
    category: "hobbies",
    price: 89000,
    compareAtPrice: null,
    stock: 96,
    sold: 960,
    description: [
      "Lapisan alumunium foil memantulkan panas tubuh kembali ke atas, sementara busa EPE menahan dingin dan lembap dari permukaan tanah.",
      "Dilipat menjadi bentuk akordeon sehingga bisa dibuka seketika tanpa perlu digulung ulang dengan rapi.",
    ],
    images: [
      { id: "terbuka", alt: "Matras lipat terbuka penuh di atas tanah." },
      { id: "terlipat", alt: "Matras dalam keadaan terlipat akordeon." },
    ],
    variants: [{ label: "Ukuran", options: ["190 x 60 cm", "190 x 90 cm"] }],
    ratings: { 5: 58, 4: 21, 3: 7, 2: 2, 1: 1 },
    reviews: [
      {
        id: "ulasan-matras-1",
        author: "Lukman H.",
        rating: 5,
        createdAt: "2026-07-31T10:45:00+07:00",
        variant: "190 x 60 cm",
        body: "Tidur di tanah basah tetap hangat. Lipatan akordeon jauh lebih praktis dibanding matras gulung.",
      },
    ],
  },
] as const satisfies readonly Product[]
